env:
    es2022: true
    browser: true
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
    - plugin:svelte/recommended
parser: "@typescript-eslint/parser"
parserOptions:
    ecmaVersion: latest
    sourceType: module
    extraFileExtensions:
        - ".svelte"
overrides:
    - files: ["*.svelte"]
      parser: "svelte-eslint-parser"
      parserOptions:
          parser: "@typescript-eslint/parser"
plugins:
    - "@typescript-eslint"
rules:
    curly: error
