# See https://pre-commit.com for more information
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.6.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
          - id: check-yaml
    - repo: https://github.com/pre-commit/mirrors-prettier
      rev: v3.1.0
      hooks:
          - id: prettier
    - repo: https://github.com/pre-commit/mirrors-eslint
      rev: v8.56.0
      hooks:
          - id: eslint
            files: \.(js|ts|svelte)$
            types: [file]
